env:
 global:
   - secure: "b7rVXw4u88Oy7oAUuggQWsGyZ+9ySDtQy9cYQoCuLzpDo114EXqEv95rwAz9UL19Sod7M7VztmA4sn/SZ5sintnywNLUjKe+G/lSsjWZ93KoEuv2o3X2RvxYI9bHB6jiwW6geGt6GFYmhW8k044ywKlK5CaYCH9z0s/GsxCg1IMMNaGF5NYPLS14ALtwkiXUMw8KZ8hkoNEmPgKjLBt/vxKXONOKDC9VGQvelxu+i6JEwXNvdcTFqU+fTZE/tK4CabwUOBNdFbIbmanbFLhzZPkvDABq7hmHR8y4yJM7ZeK9uDkGe/MSXUqlEU/SDop1gxClNTqY1H4qTgu48uHvueUXGJ08ULgp0IlckfzkSYiezg9ERNCBhN/1TX0FQ11WAW9asLNEVPuZvcKUUzaG75aAU7W4YQnt4rkpxzDiSnEPZ3RwMD62vCbr1Xl9gyhZ4bdo2z8BBuaflucvVWPDJHbBgH1nXX8lZBPezdshg+zZMsIGCUrOLo89dEWN76cEbzW8c0c+OsgzSKWzAwJ2T4hxM8xVcpbCwEMbtL5Qs5THbd9Ljm7Ot9g8BG8b+qsvsapIcpTi2uBk7AIhGR7pgQ29BQzQ9BJpG10CfIVsjPfVnZhcqefvgK5dlExNL/4UUAHS+Lrv+dUsG0COB70twl/VuA3vdxggBdi+8nd+/KM="
   - secure: "X4QhytBg5CKsMj27jQyCsFJC32HZ8aQlxZSVPiFzK5XEdePempjG1Xc8+ekJc0mtB+tbODeCO7ZVGrVOeOuec3pOM4OVC3X5GDynYWhH3j0QM3PzxUarGkt8xXByffJZ14GsTAuQQPa+B8wqVp5lz2SS7oAMhqnKdO5LS8AbhQIxGMatanjcn7nuhMxIPeijaeoca746IZLjtBRpvUOttucgBI/fC7wSNcjJrY3vzequN/HteWAUPjBWpftTkmcBKAdxKHAlHjRmkfZ91L87KsK9o8EEGYQQDJfTnvjPMR0KNgNbYo9ObgZ8G6Yx57LBbW0Klmi7eX4E9bB3HeQIcI3L0Dfe1nCXIdLpVHR6rNaonQL20UL+oxwqa73KWU+kcohNa9Ohdj8O2UwGBM0+04ocDzHHWthWcuDaFZQsTTBjIdrTz17BJLffy5rD8aoYeYg9MzVO/u25fillNUD1jq+Y86gKmyFDnsBm7cWcRSTVzapJZS32trDm7G+eGGIKkk8MV7utHC9NXup5Nyu87zjE8woCtQNZ9sbzt/KUYmLZG8BcPVTfpjlgeWmYnSuzwxqXnl4/QV+HYaiSxgR1MiI5GkNGbFd8WvIeQ6tYb1V+i4LZZXAeaLFDx25vF8VDtcip3qhcuGTb4XLsPjZP2k5Bo9xdJCl39lIgLAQGwgw="
   - secure: "YIeWwkPns4BoUYxn59N3+Qg/84v+5756D9wgQ3EwRzLe2j+iRrkUSiKLeC5ynxQDAsybaNhZ4qky22hdfbsQPaLqEZ2I6QW82fM88r0/or310uSJKujAS/eXQeUI+X3KziN6fDjlfueH+M8vvzs0zyJqW9Bbr397rhI6TluGnKisKsTfvthZwP3uys0iYdF7TbrRsdqwoilHFEUPDEVgIP37V6r1IMTzmecD7Jk49FwrIcgKlDpFCwjHLKZQbkgqObkJAYlFbFzmrL/4DB7kr7jpVjuhj6rmSDZnBB5D2kcLGOHZRgFBPiBPuNpZaRPUddpihMEX+0eweh2AcJ0VdjZDQ3kZgODEkzkHiJFZgOEUOc4Y/8DrF2wknIfzTHfx8JZRnpBi5sFaSxE6FjYW6KtPWln5HPhldI2sd/3oCX8mzFcBhtggfBPmw4O0ewTrcicTvNhK/IG71hiwK0bEZxWvVDa8wbvHcsJ92uItV+inftNw84sb0qKFmUXzBK1YfX7bi+0g7GYB+pxwSiXhHoUPxDI6qHf9o5TxskrO27nSaJJpywWE/R0J89N8RJqIFfv/8cbHkl5JfP70H/hcOvUetSV/UENCmIB26g23yAPCHC1bT3B486PiurgM4YmXBs1O8vJlciFYOQQiQQGtQWtMqhHIIHpu+reNyumQkCU="
   - secure: "AnvgTjoc+0g7BTy4izir3+2p5oYkH8XNZPcjwlT5qLQGMdJQeTLt/ry0O6IUYfhjvTA2uxTn8KLK8kP/0Pgxq4Ob3EMD9MRMriTvWXh8Gt1RQktS6mau3mSBdfzyRAsq1HXDO6ntXtKe/zr8cpsLP8RAiGzqTFWNvZ7Ns6P09lmm8fUKbCloI4JtabjogFd6z6J+K2rnL0OMaJgfIRE4bXIhg1HXRKgyTfWwbGmlk7NpS1Ww78IORwvtsZT7YkH+sK9sVKHai1ceon/52QgKYGqdYdyFxth7Gup8JNV4my0anlBIXvfCXGI4UPHvsYvR6wd9nKc5fbuBIAdHnxSjITIShWxcc1bmAb3OjW3OOEddxFpEsskhw1S2YjPf2mGBlVo47y8YeBVbSZf/6rcN7ZK/iAc1FruS7TATtTMzDgrGXYpy6yWB0L0/80H/SK/pf39By1sBCMF9iftxN3uh/aCDCt52JQq/8cRTOZKKMqV45FsSr5b8gRSVSzVKd+SVSKj7UR2CTZ1VY9WntfpOszqjflbpkT/FhzFYK+sP3LuXL2em5Lzp8CmwmyM4t2WtMlrhtmqgMzS/USZez+dgWliz3z5B2Xal9TOx4Cicc0N6NuKF0LC1XM721Ug5c00p2lJN+HDy8WHz/hERl0x7CS0kM2/lFlwpnoPgxpWpG7I="

os:
  - linux

language: minimal

services:
  - docker

before_install:
  - echo "$DOCKERHUB_PWD" | docker login --username "$DOCKERHUB_USR" --password-stdin
  - echo "$REDHAT_PWD" | docker login --username "$REDHAT_USR" --password-stdin registry.redhat.io

install:
  - docker build --file d.jboss.Dockerfile --tag juliaaano/rhpam-jboss:latest .
  # - docker build --file d.springboot.Dockerfile --tag juliaaano/rhpam-springboot:latest .

before_script:
  - docker-compose up -d --force-recreate rhpam-jboss # rhpam-springboot
  - sleep 90

script:
  - POSTMAN_ENV=rhpam-container-jboss docker-compose run --rm postman
  # - POSTMAN_ENV=rhpam-springboot docker-compose run --rm postman

after_success:
  - for i in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep "juliaaano"); do docker push $i; done
  - docker logout registry.redhat.io
  - docker logout
