env:
 global:
   - secure: "oevOlxNTCPQUZM691Eb4/SDvcWaaYdri9sdqqGUPO8Z/otGC2BicMRlcZEXBoKFfi4JSeh1Tmpxuqkj5S6yTmv7wFSvLn6Dw+pRXPI71pZipkCVJVnQnuj4yBOPXeSJ/NWHTqUHfUVo7IbdUMe8+XfREDLxeVx5FolCL2G4i7/NFo8Oe5fc+D0kAtP9x/2oMMi+iOfB40VrZ5FyRe3bLmNafwpWHs7UCsolA4Mu+TzFbinlBvr/6JqsPpTsyBMjAhCTGt25E8O3UBJTakNOgrzVt8bXjzhslILdcbwkKt/Zfuxx5aISfSPh77YrIoFsjXXSuL0rvMBN0u7CKtzEQ48uvDkylbwfFf5GV2P1kioVmligsxiugGSkG1DPNaf/LWqrcsfxSyMZxjhDh4Af0SJkN3YYNnYDqYnQ+rZ372gnn/8+g2sW9FW8u2N/7jGARh3LKzshU2Lxb1GLzW7V+o2l6p33CHvk68yNX46DeutH9I8uwkp3MJ4RZy1woWKvDNkw03rGUZTBBppz9oasUkD1xledoezJ+9KmfHZ0RlbiOv5R5FQmsludo7vl/zDA8Y110vUn9dp2SMaxq9uSroW59PqGC73oxdfF7fNfq1cu0geJdcBf8l3qetzzJsZvGEKeh2v/V2m6Uq0/L46yDSS9cgy04XpxkvQN10HKDk/s="
   - secure: "oiNTfxJTpFLMmdHSXDYHBwEJAF46o0tKDrMFGgklxaDtZsBbZ5fdLbNCoFdq0knyIp0MjpNHWF9jAj7qxjGjAld0EcN3959XFb+/Ah2v/IfJM+rtyFLl9ZLmhmw8EaykxEakTwvVqPcSfSRC7mccXb5ByPbhNRbyRpFCLGUitt5pJxQiH39AE2hch9I8DjvZld168ZOeUjJfr3ZYP7GfAnRMbB92lFEgApxLLPjaWUf1MMTt/rWu93vqIU41IMksnFMUI89U9KCMh5twL/NHAWEvZy6GbCQ2LLQ3GzycCBiHFl8NeNLhYQR+cTE3Keh+dOGDFcbxDY5kR+sMEbGcJMxxRgtMg3qF9+NXWzLMrRWPFiPSpRe3jE79XY3rINUMU9cDvv8XRcloxwNvfZs7iCYyAT2ehWbfge0CuAXLyWkxxk+S9q7mMfS4yuZvgdKwGr1kS5trlXfuWShQEzFpXX5OJPSG7w+u28l0dYVWZWAorvUCfK1TCaGIx6lqFlwZPOUxyzDWE5XU1EWqqgT1zGKJtfwLXemPsoUq/HJp/NXqtn/KtlGKHPh0k1VpCrm1LdJFztmGknzhjOZ7WZNn/NVyADA8z9rwakOCEUr/NOFsmMBCCta2GCnyMIYBf0pC81Fab8ju0MHNSGp4avk4gPDC5SYJkRKwLpu8N3eCOmE="
   - secure: "NlVWVHf7Er56k077fewtqPUiP7940nivNs4yNMO5C+Ne3+9ddZYYFVP2rkQIWyi7o+2/aiDX/o6gV8xOLIFY9v+8cEn/xli0dj4mBlpGC/z8p9DOGx520pLlr1mhtY4B0sdIZ22rbToP5Zhw+9jrJsEws8dvBSBsa/+bgO+VRFr/wy/PAviSudEVlq02vm5sRXm8NkGBA3sZ3YG8BJlWAPxiseQKZ1pk4J5KyqHXAQKoB2pVeN67OIBHm/QuTMVPBJUfZkGMJZXAcdyWEA0xj0wWLu9FqA5rgzONGhXFu+IzkCWJSSds6CiyofRHZBG5wu/kFtnJPo2htVK6CSsLzve64em+PVsoWGHlj5hi6hVzJ3SKaFjPVaANiPmyL2f6MdYGTcUS117DsGfUeKYohtUd9OBJiS4LJYZe92cf2pdPHr9luQk1avdvdKPTIHOxi8Bph0odNiqgxRQwh48mqvDLsIZSW55kTJOEX0n4FvvD+66UEtjRYb50/FxsW2ouKzFn+i698xF2N+vy8ZatYGKuxnUWe0Hus5sJVgF7nF+a46r411oMZfgJWLOqwSM98ydESHAsbKOof3PMmfwaPDofNa9r3RbBaSw0a3u4BNAPd9VULw20SQuYqODlAFhfhullFuZq+1XEtnnFdCXsMX4s7Q/yfjSRlpY4TfVvNro="
   - secure: "nfTlup8KjyoIFishEOdIKnoGspLz1r/puHxXUMEKNufjR9HloHsqyew7aJVe3Ean5mwLI8gVexXx6CmcSqkfje9MMw82fC+yJhja2RudzDSxkliJXtuQkcFgGxDkTxKmDnkeAajfy3Ps06OesXChkHGF3jAdt+A3X8WWroS5azQqgTethwxZblSVBXQy8lgZ72vgb/KFS6Vo1x2nH0RXDQcsD5cl0aQcrAB7q9uNo8XlOiFtJSU+hXNmRq/9N4DuHgl+cOXTPZmim2O1VVskn7nSc/b8I211WqPPoQRWMciGMFPrIFn17u3iZXtfeyYq3OQa+gKfnHTCVULBeKorm/c3/IQlJrSFLanrTf6yOOUYbOah76MhAl5X0LLLhZXMHf2hi7kdUWgDKN3cACeWDW5fy9JUEa0sKrxH5BoZzwRAsApHaKC1NB63QhYfLULbGZ+xEBcJ6erFSYrzLmdt6BgmBNUFvfEVKHCN60Y66xUfEfFYGO7ug5Dwcs+xQi92CKMAjOPNVUAKrij61pfDgDVo0pytlDGtcgao8SrrMRgoxFMyoFbRX1RJmlnu7daPstVjztGQ/cYVlmbN1wTamyktPxgbBckhqVdzcU/k/YTfbPn+wRPQZU2PqbY3zaygWiTZPcyzh04Z37N1gD7LQ4QQO+W6k6sxfTZN49aeoQY="

os:
  - linux

language: minimal

services:
  - docker

before_install:
  - echo "$DOCKERHUB_PWD" | docker login --username "$DOCKERHUB_USR" --password-stdin
  - echo "$REDHAT_PWD" | docker login --username "$REDHAT_USR" --password-stdin registry.redhat.io

install:
  - docker build --file d.jboss.Dockerfile --tag juliaaano/rhpam-jboss:latest .
  - docker build --file d.springboot.Dockerfile --tag juliaaano/rhpam-springboot:latest .

before_script:
  - docker-compose up -d --force-recreate rhpam-jboss rhpam-springboot
  - sleep 90

script:
  - POSTMAN_ENV=rhpam-jboss docker-compose run --rm postman
  - POSTMAN_ENV=rhpam-springboot docker-compose run --rm postman

after_success:
  - for i in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep "juliaaano"); do docker push $i; done
  - docker logout registry.redhat.io
  - docker logout
