env:
 global:
   - secure: "l7PeXT2jqZSSRlqU/6SNpdSGgpWfbgHETswK5SYgcsoa1gfbtiHunEIc7tsKDdbhU11UJdNtyYqbuZHWtDsKD9SpMk/3A/sd5wCE9Vh1GaicUyd93kaQNXUyoSmAYU2W8U5yr5o90TBNACKNtXRZRpw2jJcd1jimkC5NX7Zk0GuoGDpe5bjsc5a20pXQpB/DTLslJSf8UL1sfqVDipvhQifybewxU5aauKMgZC0nkHzFplsBwPm4g7Casn+7Kmzla+atub10afMc1JL/beSVmvKgkX5duvWDe7UCFkKUKaaWYlDV/dYGmn6m1DVZbjaK4mhcDMvF9HVJnCJ3+P0S9ZZOahIBAwAjUPjg2d3j4djboWGRQPpuZzt1YRXbYq5W0yjLxmRgopBmomdQ2864ut81Dc264Fta5DVidBvshHfcfV71LnZ18h17os0abaTNKfxaxJTT517FqnOJK4qf8uYF1VnVhV+JwdSj1t+Y8M94AU3kvwP/bmWX3yn/Zk67hTONNjxLQvfBYg59BNfhMUeX/vE4WpuexjzcO4LqXLmPjjuYGZb0rMZMNt5NK/wiGnW8x4xStf8c7fnTCNQ2XB6MwM/H5KDAT4+UGfHk8RfTpeNNfjLdFAA6bWFnRcUC9seFZNKW+Zi7UyqmgQ7XjsnpWqqZ8YpKVsVhxMNPs0E="
   - secure: "Kb5zBbG4fRcYj/PPQ6E1HGFpljOh5I2X2Eh4eF0KVac+GDi0vDrpvMXBMahvaCgox3fOGsUzv8p7D88+/M3FV0ekCA1RF/cT+SI+vqCrA1c0Y2/Y4irHQUYLZUAa+mUI+Kc7QCcorND4EVIKyVWiXZdiV/Yfc16yfzqdGUYAEcWfHPBNzSDkepFyjbCN1e4F9YKBYB+k4/mQcdUgf/yWJI4+9/maWJF6E6v95etVoAffp3X448YeLmSyzN4Q+8bCZ/5uG0GDTB87nhW2FxEkf9Dm+9/De5hazo1/Py4yRLUlX4BfhQeI4WBF+0K0KN82WPYLkrvKaMweDXR8zFzaNew5GLOiabDh5RJv+ZcJv9B0DahQTgriS0SnPBq4fIZ42vKao3khPudECuF5BQ4MYeblZ/ANJQs/ROSRWWnCkHYCdfl3uLIkX3L2aSobk3z0d4tz5duxM4T6nxhl5Ova4h4GNe1IeBvFdy0UegTyNDtv05WCk+5Jvy2ZR+lcEk4bTJc4GwrmXqx3o/WsqGqScHGtW5pFTWk1dgA6LAvmk5bSlPLZi9xii92Qsw+plfZzh+fkF1bBTNKsKmImIFQvS6hzxUOgGuvh0AvjjRIbgyRN0CaV7nrxE0GluIYb7NNHMDQBEHUfj1MBzqLngKODwuhklWU5RYezbq7pjKRC9eI="
   - secure: "Ws4SR0PiOc/m/ZSoERC+3PHvvz/FJu2vfPWWr/5c7Z50D5BDtqJvEeE9D6xLLHibk63eEpsccMreWEu8TuDftYj8+cOebrDxmBT9Z3RtBDBCjTGwQ2YyhmnLLPg1BscH0aY91kSm9tKvBU7ONzdNn1D4RK2Miqy1WBlmHe+P7SfPsDMInufKuEQ7+LfcdnrB8T8UHjffrxDhcfY2q0Au2sg5JtD/eChBLqIHzFpENKsXTsR0Ro6zQ60eMnij7BmaHDwxM9tYcFTX45xgoXK27AA4VW0QiPO1thy+++i2j57iUyO8dpacD48r0H0iTz1xvIRu9prOIghEU1P6PE/eDV64oyCCv4+3Ahf+m6qP1/gv4VSbnnuKNpfqvqyJt1MYsTbJP9Sl1fYjYdRbj+zbz6PERFMOvApw9+5hqz2Io7PtvgQFe5vJMf4jjE0vGiKCFbio4AhT3pe/q+I76ECAcf1lVg/JNnEjptFW650X0s4E71qWUWMl+ynea/d3kEtRL0GORnxmRbyrxCMS1ustG/0mPLR0er51XsDJdoHynmLqdJ0UlE075su6uC1D7FGe5ZIzif/b9uokcaifqM0YA2pHk3fGp1kc5Q1bTT3WJYUI4+90+wmkecsqq10hO67XGmzfH2Ix+Hu0YE78VikfVE/HOHhB+rWw3hImtqY3FOE="
   - secure: "IAxJPwWgl26W9bZ3WXZK+HkNiYoUjWoor0xHhG9SfLRD14R53WFKxtffOSQFivfs1hyDDH2tYKaTBYjdTJGG9aTX3LWv9/1f7BkZefYE1o7LOyxDG0znhggTifNRNFn2s3ZCWH7omfsSNOCDRshpwDgB0fHVrjUbAq3e00iHfzHCr95NUONxUHoc+N2HQ+44IkQauGvLeRxqER11dCrqomawQnRWhM13IcOz4yZ5bVYyh41ph2fwINw+t1BlT9xui17MAB0jUBi87S7V5pX7pN4mblbTjDYP5r0e2GF4Qzcxi1+AHKWu8Z0Yn0U7cCezVdixyhXcMampWQWd2ATBDlSqIkZTMJgFUcyTX6R7vE63VrwELMAEphFLJixITomd69ybB4YzvfZV/eiStR4sLdlVN1dVdq14bQXrDxtTp+6cZakFB3e0Em+ouSzhImZxBv62CVtmHKAUZWSjyAQEvVQHPQCMHGAvMQDVsXx0ctcJqW97LIpnOSDkLvrZ06q2mAFYVgW5G8opqpdj0TtxjlSzgOS70ZyTqhxhjivZFTwc8JoeCOwA6zVe1BQNXErb1fvKmkv7U7UrPYhzZhmVOQCiA4OUHS00GSUf1/CvaXlBzsgQ99HFH2Il78veBUnuQqRTe2Pactl5V5sXNPqKtLqegSgfaUsSeBue8JHKD+I="

os:
  - linux

language: minimal

services:
  - docker

# before_install:
  # - echo "$DOCKERHUB_PWD" | docker login --username "$DOCKERHUB_USR" --password-stdin
  # - echo "$REDHAT_PWD" | docker login --username "$REDHAT_USR" --password-stdin registry.redhat.io

# install:
  # - docker build --file d.jboss.Dockerfile --tag juliaaano/rhpam-jboss:latest .
  # - docker build --file d.springboot.Dockerfile --tag juliaaano/rhpam-springboot:latest .

before_script:
  - docker-compose up -d --force-recreate rhpam-jboss # rhpam-springboot
  - sleep 90

script:
  - POSTMAN_ENV=rhpam-container-jboss docker-compose run --rm postman
  # - POSTMAN_ENV=rhpam-springboot docker-compose run --rm postman

# after_success:
  # - for i in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep "juliaaano"); do docker push $i; done
  # - docker logout
  # - docker logout registry.redhat.io
