version: '3.3'

services:

  rhpam-jboss:
    image: juliaaano/rhpam-jboss:latest
    environment:
      KIE_ADMIN_USER: adminUser
      KIE_ADMIN_PWD: password
      KIE_SERVER_BYPASS_AUTH_USER: "true"
    ports:
      - target: 8080
        published: 18080
      # - target: 8443
      #   published: 18443
      # - target: 8778
      #   published: 18778
      # - target: 8888
      #   published: 18888

  rhpam-springboot:
    image: juliaaano/rhpam-springboot:latest
    ports:
      - target: 8090
        published: 18090

  postman:
    image: postman/newman:4.5.3-alpine
    command: run rhpam.postman_collection.json --environment=${POSTMAN_ENV:-rhpam-container-jboss}.postman_environment.json
    volumes:
      - type: bind
        source: ./postman
        target: /etc/newman
