package com.juliaaano.rhpam.rule;

import com.juliaaano.rhpam.data.Person;
import com.juliaaano.rhpam.data.Greeting;

rule "GreetingShadowman"
	dialect "mvel"
	ruleflow-group "greetings"
	when
		Person( name ==  "Shadowman", surname == "Red Hat" )
		$greeting: Greeting()
	then
		$greeting.setGreeting("What's up, Red Hat?");
end

rule "GreetingMemberInList"
	dialect "mvel"
	ruleflow-group "greetings"
	when
		Person( $surname: surname in ("Smith", "Johnson", "Williams", "Brown") )
		$greeting: Greeting()
	then
	    $greeting.setGreeting("Hello, " + $surname + "!");
end

query getResponse()
    $response : Greeting()
end
