package com.juliaaano.rhpam.rule;

import com.juliaaano.rhpam.data.Person;
import com.juliaaano.rhpam.data.Greeting;

rule "GreetingJohn"
	dialect "mvel"
	when
		Person( name ==  "John", surname == "Smith" )
	then
		insert ( new Greeting("Hello, John!") );
end

rule "GreetingAnyone"
	dialect "mvel"
	ruleflow-group "greeting"
	when
		$p: Person( name != null )
	then
		insert ( new Greeting("Hello, " + $p.getName() + "!") );
end

query getResponse()
    $response : Greeting()
end
