apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: quickstart
spec:
  environment: rhpam-production-immutable
  version: 7.8.0
  upgrades:
    minor: false
    enabled: false
  commonConfig:
    adminUser: adminUser
    adminPassword: password
  objects:
    console:
      replicas: 1
      env:
        - name: ORG_APPFORMER_SIMPLIFIED_MONITORING_ENABLED
          value: 'true'
    servers:
      # - name: rhpam
      #   deployments: 1
      - deployments: 1
        replicas: 3
        build:
          kieServerContainerDeployment: "rhpam-quickstart=com.juliaaano:rhpam-kjar:1.0.0-SNAPSHOT"
          gitSource:
            uri: "https://github.com/juliaaano/rhpam-quickstart"
            reference: master
            contextDir: rhpam-kjar
        database:
          type: postgresql
      # - name: rhdm
      #   deployments: 1
      #   replicas: 1
      #   build:
      #     kieServerContainerDeployment: "rhdm-quickstart=com.juliaaano:rhdm-kjar:1.0.2-SNAPSHOT"
      #     gitSource:
      #       uri: "https://github.com/juliaaano/rhdm-quickstart"
      #       reference: master
      #       contextDir: rhdm-kjar
      #   database:
      #     type: h2
